export const accessibleProfileImages = [
  {
    name: 'Bjane',
    color: '/images/profile-images/bjane.png',
    image: true,
    realImage: true,
    username: 'Bjane Quast',
  },
  {
    name: 'David',
    color: '/images/profile-images/david.png',
    image: true,
    realImage: true,
    username: 'David',
  },
  {
    name: 'Dennis',
    color: '/images/profile-images/dennis.png',
    image: true,
    realImage: true,
    username: 'dennis',
  },
  {
    name: 'Dilsher',
    color: '/images/profile-images/dilsher.png',
    image: true,
    realImage: true,
    username: 'Dilsher',
  },
  {
    name: 'Dominique',
    color: '/images/profile-images/dominique.png',
    image: true,
    realImage: true,
    username: 'Dominique',
  },
  {
    name: 'Philipp',
    color: '/images/profile-images/else.png',
    image: true,
    realImage: true,
    username: 'Else',
  },
  {
    name: 'Felix',
    color: '/images/profile-images/felix.png',
    image: true,
    realImage: true,
    username: 'Felix ',
  },
  {
    name: 'Festus',
    color: '/images/profile-images/festus.png',
    image: true,
    realImage: true,
    username: 'Festus',
  },
  {
    name: 'Jonny',
    color: '/images/profile-images/jonny.png',
    image: true,
    realImage: true,
    username: 'Jonny',
  },
  {
    name: 'Julian',
    color: '/images/profile-images/julian.png',
    image: true,
    realImage: true,
    username: 'Julian',
  },
  {
    name: 'Lion',
    color: '/images/profile-images/lion.png',
    image: true,
    realImage: true,
    username: 'Lion',
  },
  {
    name: 'Lucas',
    color: '/images/profile-images/lucas.png',
    image: true,
    realImage: true,
    username: 'Lucas',
  },
  {
    name: 'Marcel',
    color: '/images/profile-images/marcel.png',
    image: true,
    realImage: true,
    username: 'Marcel Co',
  },
  {
    name: 'Maurice',
    color: '/images/profile-images/maurice.png',
    image: true,
    realImage: true,
    username: 'MauriceSE',
  },
  {
    name: 'Merdijan',
    color: '/images/profile-images/merdo.png',
    image: true,
    realImage: true,
    username: 'Merdo141',
  },
  {
    name: 'Mick',
    color: '/images/profile-images/mick.png',
    image: true,
    realImage: true,
    username: 'Mick',
  },
  {
    name: 'Nick Cedric',
    color: '/images/profile-images/nick.png',
    image: true,
    realImage: true,
    username: 'Nick',
  },
  {
    name: 'Nicolas',
    color: '/images/profile-images/nicolas.png',
    image: true,
    realImage: true,
    username: 'NicoWerner',
  },
  {
    name: 'Patrick',
    color: '/images/profile-images/paddy.png',
    image: true,
    realImage: true,
    username: 'Patrick',
  },
  {
    name: 'Simon',
    color: '/images/profile-images/simon.png',
    image: true,
    realImage: true,
    username: 'Simon Münster',
  },
  {
    name: 'Thimo',
    color: '/images/profile-images/thimo.png',
    image: true,
    realImage: true,
    username: 'Thimo89',
  },
  {
    name: 'Tim',
    color: '/images/profile-images/tim.png',
    image: true,
    realImage: true,
    username: 'Tim',
  },
  {
    name: 'Tom',
    color: '/images/profile-images/tom.png',
    image: true,
    realImage: true,
    username: 'Tom',
  },
];
