import { Positions } from '@/interface';

export const formationNav = ['4-1-4-1', '4-4-2', '4-3-3(2)'];

/* defined formations */
export const formation_4141: Positions[] = [
  {
    pos: 'tw',
    x: 'center',
    y: 'gk',
    id: 0,
    isSelected: false,
    user: null,
  },
  {
    pos: 'riv',
    x: 'center center-right',
    y: 'cb',
    id: 1,
    isSelected: false,
    user: null,
  },
  {
    pos: 'liv',
    x: 'center center-left',
    y: 'cb',
    id: 2,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rv',
    x: 'right',
    y: 'fb',
    id: 3,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lv',
    x: 'left',
    y: 'fb',
    id: 4,
    isSelected: false,
    user: null,
  },
  {
    pos: 'zdm',
    x: 'center',
    y: 'cdm',
    id: 5,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rzm',
    x: 'center center-right',
    y: 'cm',
    id: 6,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lzm',
    x: 'center center-left',
    y: 'cm',
    id: 7,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rm',
    x: 'right',
    y: 'winger',
    id: 8,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lm',
    x: 'left',
    y: 'winger',
    id: 9,
    isSelected: false,
    user: null,
  },
  {
    pos: 'st',
    x: 'center',
    y: 'st',
    id: 10,
    isSelected: false,
    user: null,
  },
];

export const formation_442: Positions[] = [
  {
    pos: 'tw',
    x: 'center',
    y: 'gk',
    id: 0,
    isSelected: false,
    user: null,
  },
  {
    pos: 'riv',
    x: 'center center-right',
    y: 'cb',
    id: 1,
    isSelected: false,
    user: null,
  },
  {
    pos: 'liv',
    x: 'center center-left',
    y: 'cb',
    id: 2,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rv',
    x: 'right',
    y: 'fb',
    id: 3,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lv',
    x: 'left',
    y: 'fb',
    id: 4,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rzm',
    x: 'center center-right',
    y: 'cm',
    id: 5,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lzm',
    x: 'center center-left',
    y: 'cm',
    id: 6,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rm',
    x: 'right',
    y: 'winger',
    id: 7,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lm',
    x: 'left',
    y: 'winger',
    id: 8,
    isSelected: false,
    user: null,
  },
  {
    pos: 'st',
    x: 'center center-right',
    y: 'st',
    id: 9,
    isSelected: false,
    user: null,
  },
  {
    pos: 'st',
    x: 'center center-left',
    y: 'st',
    id: 10,
    isSelected: false,
    user: null,
  },
];

export const formation_443_2: Positions[] = [
  {
    pos: 'tw',
    x: 'center',
    y: 'gk',
    id: 0,
    isSelected: false,
    user: null,
  },
  {
    pos: 'riv',
    x: 'center center-right',
    y: 'cb',
    id: 1,
    isSelected: false,
    user: null,
  },
  {
    pos: 'liv',
    x: 'center center-left',
    y: 'cb',
    id: 2,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rv',
    x: 'right',
    y: 'fb fb-top',
    id: 3,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lv',
    x: 'left',
    y: 'fb fb-top',
    id: 4,
    isSelected: false,
    user: null,
  },
  {
    pos: 'zdm',
    x: 'center',
    y: 'cdm cdm-top',
    id: 5,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rzm',
    x: 'center center-right',
    y: 'cm cm-top',
    id: 6,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lzm',
    x: 'center center-left',
    y: 'cm cm-top',
    id: 7,
    isSelected: false,
    user: null,
  },
  {
    pos: 'rf',
    x: 'right',
    y: 'winger winger-top',
    id: 8,
    isSelected: false,
    user: null,
  },
  {
    pos: 'lf',
    x: 'left',
    y: 'winger winger-top',
    id: 9,
    isSelected: false,
    user: null,
  },
  {
    pos: 'st',
    x: 'center',
    y: 'st',
    id: 10,
    isSelected: false,
    user: null,
  },
];
